### ISSUE TITLE
Cadastro de Turma

### ISSUE THREAD

**Issue by connorharu** [virocha11/Supervelha-SPA#1]
**História de Usuário**
Como professor, desejo cadastrar uma turma para agrupar os alunos e realizar atividades de uma maneira mais rápida.

**Critérios de Aceitação**

- [x] cadastro eficiente de uma turma no sistema; 
- [x] um código de turma é gerado automaticamente;

**Comment by taisbarbosa** [comment]
Cadastro eficiente: (https://github.com/virocha11/Supervelha-SPA/commit/6754172c4e7c4ddb2716d3ccdc25e81837d2b93d) - cadastrar turma, https://github.com/virocha11/Supervelha-SPA/commit/77baa49807f92a423d4496f19c3078ab97457fbe, https://github.com/virocha11/Supervelha-SPA/commit/c70e07ee65f1b3cac095417e5dd37b132a22304e, https://github.com/virocha11/Supervelha-SPA/commit/324b20586b9741cf3a776614e35a704b8c3b33f4#diff-8a2e7fb22138a81e52a3dc93b6f1abd749b779982efcd7b60eb395b96c538a59.

Código automaticamente:  (https://github.com/virocha11/Supervelha-SPA/commit/6754172c4e7c4ddb2716d3ccdc25e81837d2b93d).

**Comment by connorharu** [comment]
[a91591d](https://github.com/virocha11/Supervelha-SPA/commit/a91591d85f5902857554fec2b019fa50e5c07e81) - front end de cadastro_turma
[3748790](https://github.com/virocha11/Supervelha-SPA/commit/374879075fe1ac7d40f22d91a4ed3938d5b63094) - excluir turma
[20459b3](https://github.com/virocha11/Supervelha-SPA/commit/20459b3d51ced974320c6296d5885375dd231e94) - modificações no front end de turma
